### PR TITLE
Fix completion

### PR DESCRIPTION
**Pull request by ghost**
Fixed actually 2 issues:
- Like most commands, the output of `man -w` ends with a newline, and
  `system()` does not strip it automatically. Add `\n` as a separator when
  splitting, this is a concise way to get rid of it here.
- On most Linux systems, manpages are gzip'd, their name are hence
  `<name>.<section>.gz`. Fix the regex to take that into account when
  transforming the filename (discarding any extension).

### CODE REVIEW

**Comment by ghost** [comment]
Some suggestions (nothing to do with this issue, but I thought you might appreciate some feedback):
- Avoid prefixing local variables with `l:` inside functions, this is unnecessary and very noisy when you have a lot of local variables such as in this function.
- Looking at the commented-out code, you can't rely on `$MANPATH` simply because it's usually not set. That said, you could add its contents to `man -w`, if it is set. You should remove the commented-out code, your new globbing is much better and there's no point leaving such comments (that's what a commit log is there for).

**Comment by nhooyr** [comment]
Thanks! 

That code is commented out because it causes a bug in vim itself, I've gotta to send a bug report so I just left it there. 

Hmm, I'm surprised as well that no one else reported this and the fact that I missed it, I use OSX mostly but I do use linux on a few servers and I completely forgot about testing the autocomplete there...

Is the first change necessary? Second change looks good.

**Comment by nhooyr** [comment]
Ah never mind, second change won't work. Some man page names can actually have a period in them, e.g. `ip2cc5.16` on OSX. Or `net_if.h` on linux.

**Comment by ghost** [comment]
> That code is commented out because it causes a bug in vim itself, I've gotta to send a bug report so I just left it there.

Oh really? Interesting, what's the issue?

> Is the first change necessary? Second change looks good.

Yes it is, that's actually the reason why I had no completion result at all. After fixing it, I got results, albeit wrong ones (badly formatted because of the .gz issue). You possibly don't see that on OS X because newlines are `\r` instead of `\n`, but at least on Linux it completely breaks `globpath()` since the last path returned by `man -w` will end with a newline that will make the glob fail, and in my case the last path is actually the one that matters.
For the record, 0cc42fd still doesn't work for me because of this.

> Ah never mind, second change won't work. Some man page names can actually have a period in them, e.g. ip2cc5.16 on OSX. Or net_if.h on linux.

That's completely right, I realised afterwards that I overlooked this.  f09e8b2 works properly for me after fixing the newline issue, I originally thought your regex could be simplified but in the end I think your regex is quite optimal. That said, if you want to be comprehensive it looks like other extensions are possible, as per the man completion script: https://github.com/scop/bash-completion/blob/master/completions/man#L11

**Comment by nhooyr** [comment]
@Corax26 I forgot, had something to do with the autocomplete not functioning properly, i'll take a look at it some other day.

Ah you are right about the newline, never noticed because for me the last directory is for 1 manpage. I'll add in the extra extensions to the regex. I'll close this for now, any further discussion lets continue at #14.

**Pull request closed without merging**
