### PR TITLE
Add an option to Make :Tnman open a tab after the current tab

### PR DESCRIPTION
**Pull request by ghost**
Tab command variants are expected to open a tab after the current one, not before it.

### CODE REVIEW

**Comment by nhooyr** [comment]
This was intentional because you can close the new tab and you will return to the previous tab instead of the next one.

**Comment by ghost** [comment]
Oh I see. Would it make sense to introduce a config option then?

**Comment by nhooyr** [comment]
@Corax26 I wouldn't mind. Just ensure that the behaviour is tabs appear behind by default. Go ahead and add the option and I'll merge.

**Comment by ghost** [comment]
@nhooyr Great, this new commit should suit you better.

**Comment by nhooyr** [comment]
Great thank you.

**Comment by ghost** [comment]
Cheers!

**Pull request merged**
