### PR TITLE
Efficiently finds the default section of a manpage

### LINKED ISSUE #1: Error when opening man page
Hi. I'm trying out neoman now. I get this error when I try to open a man page with `:Neoman printf`:

```
Error detected while processing function neoman#get_page:
line   50:
E172: Only one file name allowed: edit man://printf(25               January 201
6                        PRINTF(1)
```

I use the following minimal vimrc file:

``` vim
set nocompatible
let &rtp = '~/.vim/bundle/neoman.vim,' . &rtp
filetype plugin indent on
syntax enable
```

I'm on a recently updated Arch Linux with vim/gvim version 7.4.1294.

### PR DESCRIPTION
**Pull request by nhooyr**
This fixes #1. Moved to using the -w flag of man. Much easier now.

### CODE REVIEW

**Comment by sunaku** [comment]
:+1: Works great!  Tested my own projects' man pages as well as system ones.  `<C-]>` resolves correctly. :shipit:

**Comment by nhooyr** [comment]
@sunaku great, I'm gonna just wait a little bit before merging. I've been committing to master too impulsively without any testing. 

Also specifically test what the buffer is named. It should always be `page(sect)`. Always! It should be able to determine the section even if you give no section.

**Comment by nhooyr** [comment]
I also added some small fixes.

**Comment by nhooyr** [comment]
Think its ready to merge now.

**Comment by lervag** [comment]
Great, good work!

**Pull request merged**
